#!/usr/local/bin/expect

set USERNAME $env(USER_NAME)
set PASSWORD $env(PASS_WORD)
set timeout 2

set FILENAME [lindex $argv 0];
set DBHOST [lindex $argv 1];

if { ! [file exists $FILENAME]} {
  puts "File $FILENAME not found"
  exit 1
}

set result [exec ~/scripts/lookup_bastion $DBHOST]
set output_array [split $result ";"]

set BASTION [lindex $output_array 0];
set DBAJUMP [lindex $output_array 1];
spawn scp -oProxyJump=$BASTION,$DBAJUMP $FILENAME $USERNAME@$DBHOST:/home/ppbhatta
expect {
    "yes/no" {
        send "yes\r"
        exp_continue
    }
    "assword:" {
        send "$PASS_WORD\r"
        exp_continue
    }
}
